### ISSUE TITLE
Support to Android 5.0.0 and iOS 6.0.0

### ISSUE THREAD

**Issue by CoderGamester** [Majchrzak/Flurry-Unity-3D#1]
Hi,

Are you planning to support the unity plugin for the lates Flurry version iOS 6.0.0 and Android 5.0.0? With the new API this plugin doesn’t work :(

Cheers,

**Comment by Majchrzak** [comment]
Hi,

Yes, there will be support for new version of Flurry as soon as possible.

**Comment by Majchrzak** [comment]
Done.
