### ISSUE TITLE
Correct setup for AndroidManifest.xml

### ISSUE THREAD

**Issue by ryukbk** [Majchrzak/Flurry-Unity-3D#4]
Hello, the README.md says these lines are necessary in the AndroidManifest.xml for Android setup,

meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ APP_ID" /
meta-data android:name="com.google.android.gms.appstate.APP_ID" android:value="\ APP_ID" /

but the current Google Play Game Services document
http://developer.android.com/google/play-services/setup.html#Setup/
says only this line is necessary:

meta-data android:name="com.google.android.gms.version"
           android:value="@integer/google_play_services_version" /

Which is correct?

**Comment by Majchrzak** [comment]
Looks like com.google.android.gms.appstate.APP_ID is not required.

Thanks.
