### ISSUE TITLE
iOS Event Parameters inverted on Flurry - **BUG FIX**

### ISSUE THREAD

**Issue by rcstuber** [Majchrzak/Flurry-Unity-3D#6]
There is a **critical bug** in the iOS Wrapper, which causes Event Parameters to be swapped at the parameter key and the parameter value.

Following line in function _keyValueToDict_ in UnityFlurry.mm is wrong:

[dict setObject:[keysArray objectAtIndex: i] forKey:[valuesArray objectAtIndex: i]];

CHANGE TO:
**[dict setObject:[valuesArray objectAtIndex: i] forKey:[keysArray objectAtIndex: i]];**

Sadly Objective-C is being one of those languages where a Map is set in the form of value/key instead the other ways around!

Hope it helps. Cheers.

**Comment by Majchrzak** [comment]
Thanks, fixed.
